WebUI/Areas/Sales/Controllers/OrderHeaderController.cs
using Data.Entities;
using Data.Entities.Sales;
using Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.Controllers;
using WebUI.Areas.Sales.Models;

namespace WebUI.Areas.Sales.Controllers
{
    [Area("Sales")]
    public class OrderHeaderController : BaseController<Order, OrderDto, OrderLineDto>
    {

        public OrderHeaderController(IRepoService _repo, IMapperService _mapper, IIdentityService _idService)
            : base(_repo, _mapper)
        {
        }


        public override OrderDto PopulateSelectLists(OrderDto dto)
        {
            // Normally I would create a lookup/OptionsList table to store all the options
            dto.OrderTypeList = [
                new SelectListItem { Text = "Normal", Value = "Normal" },
                new SelectListItem { Text = "Staff", Value = "Staff" },
                new SelectListItem { Text = "Mechanical", Value = "Mechanical" },
                new SelectListItem { Text = "Perishable", Value = "Perishable" }
            ];

            dto.OrderStatusList = [
                new SelectListItem { Text = "New", Value = "Normal" },
                new SelectListItem { Text = "Processsing", Value = "Processsing" },
                new SelectListItem { Text = "Complete", Value = "Complete" },
                new SelectListItem { Text = "On Hold", Value = "On Hold" }
            ];
            return base.PopulateSelectLists(dto);
        }

        public override OrderDto DefaultValuesGet(OrderDto dto, bool isNew, string queryParam)
        {
            dto.Status = "New";
            return base.DefaultValuesGet(dto, isNew, queryParam);
        }
    }
}

WebUI/Views/Shared/_Config.cshtml
<script>
    var siteOptions = {};
</script>

WebUI/Views/Shared/_IndexPartial.cshtml
<div>
    <div class="modal-header">
        <h6 class="modal-title"><span class="f-w-600">@ViewData["Title"]</span></h6>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-toolbar">
                    <button type="button " class="btn btn-outline-danger btn-sm btn-pure float-right" data-dismiss="modal"><i class="far fa-window-close"></i>Close</button>
                </div>
                <div class="modal-controls">
                    <div class="card">
                        <div class="card-block">
                            <partial name="Index" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <partial name="_ModalScripts" />
</div>

WebUI/Views/Shared/_Layout.cshtml
@{
    var activeMenu = ViewData["menu"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - DPW Nickson Assessment</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="#">
    <meta name="author" content="Nickson Mwangi - Software Developer">
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bundles/app.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nickson Assessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Sales" asp-controller="OrderHeader" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="modal-holder">
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Nickson Assessment - Niclausel@gmail.com - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <partial name="_Config" />
    <script src="~/js/bundles/jquery.min.js"></script>
    <script src="~/js/bundles/layout.min.js"></script>
    <script src="~/js/bundles/modernizr.min.js"></script>
    <script src="~/js/bundles/table.min.js"></script>
    <script src="~/js/bundles/plugin.min.js"></script>
    <script src="~/lib/select-table/select-table.js"></script>
    <script src="~/js/bundles/i18next.min.js"></script>
    <script src="~/js/bundles/common.min.js"></script>
    @RenderSectionAsync("Scripts", required: false)

    @{
        var displayMsg = ViewData["alert"] ?? ViewData["alert"];
        if (displayMsg != null && !string.IsNullOrEmpty(displayMsg.ToString()))
        {
            <script>
                @Html.Raw(displayMsg)
            </script>
        }
    }
</body>
</html>

WebUI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>DPW Assessment - Login</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="#">
    <meta name="author" content="Nickson Mwangi - Senior Full Stack Developer">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebUI.styles.css" asp-append-version="true" />

    <link rel="shortcut icon" href="~/images/favicon.ico">
    @*   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">*@

    <link rel="stylesheet" href="~/css/bundles/login.min.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <div class="container mt-5">
            @RenderBody()
        </div>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @{
        var displayMsg = ViewData["alert"] ?? ViewData["alert"];
        if (displayMsg != null && !string.IsNullOrEmpty(displayMsg.ToString()))
        {
            <script>
                @Html.Raw(displayMsg)
            </script>
        }
    }
</body>
</html>

WebUI/Views/Shared/_ModalScripts.cshtml
<script src="~/js/bundles/jqueryui.min.js"></script>
<script src="~/js/bundles/jqueryval.min.js"></script>
<script src="~/js/bundles/controls.min.js"></script>
<script src="~/js/assets/header.js"></script>
@*<partial name="_Config" />*@

WebUI/Views/Shared/_RowActionButton.cshtml
@using Library.Utility
@model List<ActionLinkModel>
@{
    string ddname = string.Format("ddb_{0}", Model.FirstOrDefault().LinkId);
    string viewarea = ViewContext.RouteData.Values.ContainsKey("area") ? ViewContext.RouteData.Values["area"].ToString() : "";
    string viewcontroller = ViewContext.RouteData.Values["controller"].ToString();
}
<div class="dropdown">
    <button id="@ddname" class="btn btn-outline-primary btn-mini dropdown-btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-ellipsis-h"></i>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        @foreach (var lnk in Model)
        {
            var larea = lnk.LinkArea ?? viewarea;
            var lcontroller = lnk.LinkController ?? viewcontroller;
            <a class="dropdown-item waves-light waves-effect @lnk.LinkClass" asp-area=@larea
               asp-controller=@lcontroller asp-action=@lnk.LinkAction asp-all-route-data=@lnk.LinkRoute data-load="">
                <i class="@lnk.LinkIcon"></i>@lnk.LinkName
            </a>
        }
    </div>
</div>

WebUI/Views/Shared/_TableFormatter.cshtml
<script>
    function actionFormatter(value, row, index) {
        var rowActions = "";
        $.ajax({
            async: false,
            url: '@Url.Action("RowActionButton")',
            data: { linkModels: JSON.stringify(value) },
            success: function (data) {
                rowActions = data;
            }
        });
        return rowActions;
    }

    function dateFormatter(value, row, index) {
        return moment(value).format('DD MMM YYYY');
    }

    function dateSorter(a, b) {
        //if (new Date(a.toDate()) < new Date(b.toDate())) return 1;
        //if (new Date(a.toDate()) > new Date(b.toDate())) return -1;
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
    }


    window.actionEvents = {
        'click .show-modal': function(e) {
            e.preventDefault();
            var url = $(e.currentTarget).attr('href');
            var modalTarget = $(e.currentTarget).data('target');
            Common.displayModal(url, modalTarget);
        }
    }

    $(function () {
        Common.blockerLink();
    });
</script>